// Load environment variables from .env.local
require('dotenv').config({ path: '.env.local' });

const fs = require('fs');
const path = require('path');

console.log('🔍 Debug: Environment Variables');
console.log('SUPABASE_URL:', process.env.SUPABASE_URL ? '✅ Loaded' : '❌ Missing');
console.log('SUPABASE_AUTH:', process.env.SUPABASE_AUTH ? '✅ Loaded' : '❌ Missing');
console.log('SUPABASE_APIKEY:', process.env.SUPABASE_APIKEY ? '✅ Loaded' : '❌ Missing');
console.log('');

// Configuration (now loaded from .env.local)
const SUPABASE_PROJECT_URL = process.env.SUPABASE_URL || 'https://xxxxxxxxxxxxx.supabase.co';
const SUPABASE_AUTH = process.env.SUPABASE_AUTH;
const SUPABASE_APIKEY = process.env.SUPABASE_APIKEY;

// Validate environment variables
if (!SUPABASE_AUTH || !SUPABASE_APIKEY) {
  console.error('❌ Error: SUPABASE_AUTH and SUPABASE_APIKEY environment variables are required');
  console.error('Missing:', {
    SUPABASE_AUTH: SUPABASE_AUTH ? '✅' : '❌',
    SUPABASE_APIKEY: SUPABASE_APIKEY ? '✅' : '❌'
  });
  process.exit(1);
}

// Edge Function endpoints
const ENDPOINTS = {
  projects: `${SUPABASE_PROJECT_URL}/functions/v1/get-projects`,
  workExperience: `${SUPABASE_PROJECT_URL}/functions/v1/get-work-experience`,
  education: `${SUPABASE_PROJECT_URL}/functions/v1/get-education`,
  blogPosts: `${SUPABASE_PROJECT_URL}/functions/v1/get-blog-posts`,
  systemMapLinks: `${SUPABASE_PROJECT_URL}/functions/v1/get-system-map-links`
};

/**
 * Fetch data from Supabase Edge Function
 */
async function fetchFromSupabase(endpoint, name) {
  console.log(`📡 Fetching ${name}...`);
  
  try {
    const response = await fetch(endpoint, {
      headers: {
        'Authorization': SUPABASE_AUTH,
        'apikey': SUPABASE_APIKEY,
        'Content-Type': 'application/json'
      }
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`HTTP ${response.status}: ${response.statusText}\n${errorText}`);
    }

    const data = await response.json();
    console.log(`✅ Fetched ${data.length || 0} ${name}`);
    return data;
  } catch (error) {
    console.error(`❌ Error fetching ${name}:`, error.message);
    throw error;
  }
}

/**
 * Convert icon strings to import statements
 */
function generateIconImports(data) {
  const icons = new Set();
  
  // Extract unique icon names from all data
  data.forEach(item => {
    if (item.icon) icons.add(item.icon);
  });
  
  return Array.from(icons).sort();
}

/**
 * Generate constants.js file content
 */
function generateConstantsFile(projects, workExperience, education, blogPosts, systemMapLinks) {
  // Collect all unique icons
  const allIcons = generateIconImports([
    ...projects,
    ...workExperience,
    ...education
  ]);

  const timestamp = new Date().toISOString();

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated: ${timestamp}
 * Source: Supabase Edge Functions
 * 
 * This file is automatically generated by scripts/fetch-data.js
 * Run 'npm run fetch-data' to regenerate
 */

import { ${allIcons.join(', ')} } from 'lucide-react';

// ============================================
// PERSONAL INFORMATION (Hardcoded - rarely changes)
// ============================================

export const PERSONAL_INFO = {
  name: 'Vineeth Kirandumkara',
  email: 'vineethkirandumkara+portfolio@gmail.com',
  location: 'London, UK',
  tagline: 'IoT Systems Engineer & Connected Product Designer',
  bio: 'Passionate about creating intelligent, connected systems that bridge the physical and digital worlds.',
  expectedGraduation: 'Summer 2025'
};

export const SOCIAL_LINKS = {
  linkedin: {
    url: 'https://www.linkedin.com/in/vineeth-kirandumkara-3b322924',
    displayUrl: 'linkedin.com/in/vineeth-kirandumkara',
    icon: 'Linkedin',
    label: 'LinkedIn',
    color: 'text-blue-600'
  },
  github: {
    url: 'https://github.com/vineethk96',
    displayUrl: 'github.com/vineethk96',
    icon: 'Github',
    label: 'GitHub',
    color: 'text-gray-700 dark:text-gray-300'
  }
};

export const EXTERNAL_LINKS = {
  calendly: 'https://calendly.com/vineethk96',
  resume: '/vineethCV.pdf'
};

export const PERSONAL_STORY = {
  introduction: "I'm an embedded systems engineer transitioning to IoT architecture and product design. My journey spans from low-level firmware to cloud-connected systems, with a passion for creating technology that scales from prototype to mass market.",
  journey: [
    "My path in technology began with a fascination for how things work at the most fundamental level. During my computer engineering studies at Virginia Tech, I dove deep into embedded systems, digital design, and the intricate dance between hardware and software.",
    "Over the past five years, I've worked across various startups and established companies, building everything from UAV control systems to battery safety monitors. Each role has expanded my perspective from component-level optimization to system-level architecture.",
    "Now, pursuing my MSc in Connected Environments at UCL, I'm focused on the bigger picture: how connected devices can create meaningful experiences for people and communities. I'm passionate about bridging the gap between technical capability and human need, designing IoT systems that are not just functional, but truly valuable at scale."
  ],
  vision: "I'm excited to join teams that are building the next generation of connected products. My goal is to work at the intersection of IoT systems, product design, and user experience, creating technology that seamlessly integrates into people's lives and scales to serve millions of users worldwide."
};

export const SKILLS = {
  'Embedded Systems': {
    icon: 'Zap',
    skills: ['C/C++', 'FreeRTOS', 'ESP32/Arduino', 'PCB Design', 'Signal Processing'],
    color: 'text-blue-500'
  },
  'IoT & Cloud': {
    icon: 'Globe',
    skills: ['MQTT', 'AWS/Cloud Services', 'REST APIs', 'Data Analytics', 'System Architecture'],
    color: 'text-green-500'
  },
  'Software Development': {
    icon: 'Code',
    skills: ['Python', 'JavaScript/React', 'Flutter', 'Git', 'Agile/Scrum'],
    color: 'text-purple-500'
  },
  'Design & Prototyping': {
    icon: 'Target',
    skills: ['Product Design', 'User Research', 'CAD/3D Modeling', 'Rapid Prototyping', 'UI/UX'],
    color: 'text-pink-500'
  }
};

// ============================================
// DYNAMIC DATA (Fetched from Supabase)
// ============================================

export const PROJECTS = ${JSON.stringify(projects.map(p => ({
  ...p,
  icon: p.icon // Will be replaced with actual component reference
})), null, 2).replace(/"icon":\s*"(\w+)"/g, 'icon: $1')};

export const WORK_EXPERIENCE = ${JSON.stringify(workExperience.map(w => ({
  ...w,
  icon: w.icon
})), null, 2).replace(/"icon":\s*"(\w+)"/g, 'icon: $1')};

export const EDUCATION = ${JSON.stringify(education.map(e => ({
  ...e,
  icon: e.icon
})), null, 2).replace(/"icon":\s*"(\w+)"/g, 'icon: $1')};

export const BLOG_POSTS = ${JSON.stringify(blogPosts, null, 2)};

export const SYSTEM_MAP_LINKS = ${JSON.stringify(systemMapLinks, null, 2)};

// ============================================
// DERIVED DATA
// ============================================

export const TIMELINE_DATA = [
  ...EDUCATION,
  ...WORK_EXPERIENCE
].sort((a, b) => {
  const getStartYear = (item) => item.start_year || parseInt(item.year?.split('–')[0] || item.year?.split('-')[0] || 0);
  return getStartYear(b) - getStartYear(a);
});

export const CONTACT_INFO = [
  {
    icon: 'Mail',
    label: 'Email',
    value: PERSONAL_INFO.email,
    href: \`mailto:\${PERSONAL_INFO.email}\`,
    color: 'text-blue-500'
  },
  {
    icon: 'MapPin',
    label: 'Location',
    value: PERSONAL_INFO.location,
    href: null,
    color: 'text-green-500'
  },
  {
    icon: 'Linkedin',
    label: SOCIAL_LINKS.linkedin.label,
    value: SOCIAL_LINKS.linkedin.displayUrl,
    href: SOCIAL_LINKS.linkedin.url,
    color: SOCIAL_LINKS.linkedin.color
  },
  {
    icon: 'Github',
    label: SOCIAL_LINKS.github.label,
    value: SOCIAL_LINKS.github.displayUrl,
    href: SOCIAL_LINKS.github.url,
    color: SOCIAL_LINKS.github.color
  }
];

// Certifications
export const CERTIFICATIONS = [
  {
    name: 'Autodesk Inventor Professional',
    issuer: 'Autodesk',
    year: '2019',
    description: 'Advanced 3D CAD design and mechanical engineering'
  }
];
`;
}

/**
 * Main execution
 */
async function main() {
  console.log('🚀 Starting data fetch from Supabase...\n');

  try {
    // Fetch all data in parallel
    const [projects, workExperience, education, blogPosts, systemMapLinks] = await Promise.all([
      fetchFromSupabase(ENDPOINTS.projects, 'projects'),
      fetchFromSupabase(ENDPOINTS.workExperience, 'work experience'),
      fetchFromSupabase(ENDPOINTS.education, 'education'),
      fetchFromSupabase(ENDPOINTS.blogPosts, 'blog posts'),
      fetchFromSupabase(ENDPOINTS.systemMapLinks, 'system map links')
    ]);

    console.log('\n📝 Generating constants.js...');

    // Generate constants.js content
    const content = generateConstantsFile(
      projects,
      workExperience,
      education,
      blogPosts,
      systemMapLinks
    );

    // Write to file
    const outputPath = path.join(__dirname, '..', 'src', 'data', 'constants.js');
    fs.writeFileSync(outputPath, content, 'utf8');

    console.log(`✅ Successfully generated: ${outputPath}`);
    console.log('\n📊 Summary:');
    console.log(`   - Projects: ${projects.length}`);
    console.log(`   - Work Experience: ${workExperience.length}`);
    console.log(`   - Education: ${education.length}`);
    console.log(`   - Blog Posts: ${blogPosts.length}`);
    console.log(`   - System Map Links: ${systemMapLinks.length}`);
    console.log('\n✨ Done!\n');

  } catch (error) {
    console.error('\n❌ Fatal error:', error.message);
    process.exit(1);
  }
}

// Run the script
main();